#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : typing
Version  : 3.6.2
Release  : 1
URL      : http://pypi.debian.net/typing/typing-3.6.2.tar.gz
Source0  : http://pypi.debian.net/typing/typing-3.6.2.tar.gz
Summary  : Type Hints for Python
Group    : Development/Tools
License  : Python-2.0
Requires: typing-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
This is a backport of the standard library typing module to Python
        versions older than 3.5.
        
        Typing defines a standard notation for Python function and variable
        type annotations. The notation can be used for documenting code in a
        concise, standard format, and it has been designed to also be used by
        static and runtime type checkers, static analyzers, IDEs and other
        tools.

%package python
Summary: python components for the typing package.
Group: Default

%description python
python components for the typing package.


%prep
%setup -q -n typing-3.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503151908
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503151908
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
